### ISSUE TITLE
Extension fails to load after upgrade to v0.6.0

### ISSUE THREAD

**Issue by cmuhire** [elixir-lsp/vscode-elixir-ls#145]
### Environment

- Elixir & Erlang versions (elixir --version): Elixir 1.10.3, Erlang/OTP 22 
- VSCode ElixirLS version: v0.6.0
- Operating System Version: Linux (Ubuntu 16.04)

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor

1.  Create a new Mix project with `mix new empty`, then open that project with VS Code and open an Elixir file. Is your issue reproducible on the empty project? If not, please publish a repo on Github that does reproduce it.
2.  Check the output log by opening `View > Output` and selecting "ElixirLS" in the dropdown. Please include any output that looks relevant. (If ElixirLS isn't in the dropdown, the server failed to launch.)
3.  Check the developer console by opening `Help > Toggle Developer Tools` and include any errors that look relevant.

---

### Description

The extension fails to properly load after upgrading to v0.6.0. Syntax highlighting works but other features like autocompletion, navigation, deps fetching and PLT build do not work and the extension does not appear in the dropdown under `View > Output`.

A `Cannot find module 'shelljs'` error is printed in the DevTools console.
![elixir_ls](https://user-images.githubusercontent.com/6691440/95008455-4d41b400-061a-11eb-8017-9567be2c3624.png)

![elixir_ls](https://user-images.githubusercontent.com/6691440/95008458-55015880-061a-11eb-8774-47d65284ec5e.gif)

**Comment by jeramyRR** [comment]
I'm experiencing the same.  This is the error I'm getting:

[2020-10-04 06:48:35.485] [exthost] [error] Activating extension JakeBecker.elixir-ls failed due to an error:
[2020-10-04 06:48:35.486] [exthost] [error] Error: Cannot find module 'shelljs'
Require stack:
- /root/.vscode-server/extensions/jakebecker.elixir-ls-0.6.0/out/extension.js
- /root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/loader.js
- /root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/bootstrap-amd.js
- /root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
	at Function.Module._load (internal/modules/cjs/loader.js:686:27)
	at Function.t._load (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1070:268)
	at Function.i._load (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1039:981)
	at Function.n._load (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1036:303)
	at Module.require (internal/modules/cjs/loader.js:848:19)
	at require (internal/modules/cjs/helpers.js:74:18)
	at Object.<anonymous> (/root/.vscode-server/extensions/jakebecker.elixir-ls-0.6.0/out/extension.js:10:15)
	at Module._compile (internal/modules/cjs/loader.js:955:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
	at Module.load (internal/modules/cjs/loader.js:811:32)
	at Function.Module._load (internal/modules/cjs/loader.js:723:14)
	at Function.t._load (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1070:268)
	at Function.i._load (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1039:981)
	at Function.n._load (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1036:303)
	at Module.require (internal/modules/cjs/loader.js:848:19)
	at require (internal/modules/cjs/helpers.js:74:18)
	at Function.s [as __$__nodeRequire] (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/loader.js:33:604)
	at p._loadCommonJSModule (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1041:241)
	at p._doActivateExtension (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:939:625)
	at p._activateExtension (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:938:708)
	at Object.actualActivateExtension (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:936:453)
	at h._activateExtension (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:668:731)
	at /root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:668:409
	at Array.map (<anonymous>)
	at h._activateExtensions (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:668:397)
	at h.activateByEvent (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:665:919)
	at p._activateByEvent (/root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:937:300)
	at /root/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:946:242
	at processTicksAndRejections (internal/process/task_queues.js:94:5)

**Comment by iporsut** [comment]
I think it's about `vsce` use wrong version that compatible with currently of extension.

I try to manual package with `npx vsce package` it will used `vsce` version `1.75.0`. Then install it manually it doesn't have above error.

But when I use `vsce` version `1.81.0` from global `npm install -g vsce` to package and install manually I found same error above.

**Comment by iporsut** [comment]
Seem like `vsce`  `1.81.0` detected to `useYarn` in this project. So it doesn't get npm dependencies. We have to force it that not use yarn by `vsce package --no-yarn`.

**Comment by crbelaus** [comment]
Ouch. I've experienced the same bug and created issue elixir-lsp/elixir-ls#372. Since this is an error related to the VSCode extension itself I am closing that issue.

**Comment by iporsut** [comment]
🆗 I found this issue https://github.com/microsoft/vscode-vsce/issues/494 to confirm that it's bug from `vsce` https://github.com/microsoft/vscode-vsce/issues/494

**Comment by cmuhire** [comment]
I'm not sure that the issue is due to `vsce` version, it may rather be with the publishing stage.

The extension that I packaged locally with latest `vsce` version does include a `node_modules` folder (left pane in screenshot below) and loads fine when installed, but the one downloaded from the marketplace does not include a `node_modules` folder (right pane in screenshot below) which is why the `shelljs` module can't be found.
![elixir_ls_diff](https://user-images.githubusercontent.com/6691440/95013034-c7376480-063d-11eb-99a0-56b14261c31a.png)

@axelson making sure the `node_modules` folder is included in the next published version should fix the issue.

P.S: worth considering using Webpack in the future to produce a single, slimmer bundle as recommended here https://code.visualstudio.com/api/working-with-extensions/bundling-extension
![elixir_ls_suggestion](https://user-images.githubusercontent.com/6691440/95013148-9c99db80-063e-11eb-9d37-cfd1624efd08.png)

**Comment by xpyxel** [comment]
Can confirm, it's broken for me as well

```
[2020-10-04 08:22:40.840] [exthost] [error] Activating extension JakeBecker.elixir-ls failed due to an error:
[2020-10-04 08:22:40.843] [exthost] [error] Error: Cannot find module 'shelljs'
Require stack:
- /home/pyxel/.vscode-server/extensions/jakebecker.elixir-ls-0.6.0/out/extension.js
- /home/pyxel/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/loader.js
- /home/pyxel/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/bootstrap-amd.js
- /home/pyxel/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
	at Function.Module._load (internal/modules/cjs/loader.js:686:27)
	at Function.t._load (/home/pyxel/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1070:268)
	at Function.i._load (/home/pyxel/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1039:981)
	at Function.n._load (/home/pyxel/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1036:303)
	at Module.require (internal/modules/cjs/loader.js:848:19)
	at require (internal/modules/cjs/helpers.js:74:18)
	at Object.<anonymous> (/home/pyxel/.vscode-server/extensions/jakebecker.elixir-ls-0.6.0/out/extension.js:10:15)
	at Module._compile (internal/modules/cjs/loader.js:955:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
	at Module.load (internal/modules/cjs/loader.js:811:32)
	at Function.Module._load (internal/modules/cjs/loader.js:723:14)
	at Function.t._load (/home/pyxel/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1070:268)
	at Function.i._load (/home/pyxel/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1039:981)
	at Function.n._load (/home/pyxel/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1036:303)
	at Module.require (internal/modules/cjs/loader.js:848:19)
	at require (internal/modules/cjs/helpers.js:74:18)
	at Function.s [as __$__nodeRequire] (/home/pyxel/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/loader.js:33:604)
	at p._loadCommonJSModule (/home/pyxel/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:1041:241)
	at p._doActivateExtension (/home/pyxel/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:939:625)
	at p._activateExtension (/home/pyxel/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:938:708)
	at Object.actualActivateExtension (/home/pyxel/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:936:453)
	at h._activateExtension (/home/pyxel/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:668:731)
	at /home/pyxel/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:668:409
	at Array.map (<anonymous>)
	at h._activateExtensions (/home/pyxel/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:668:397)
	at h.activateByEvent (/home/pyxel/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:665:919)
	at p._activateByEvent (/home/pyxel/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:937:300)
	at /home/pyxel/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/out/vs/server/remoteExtensionHostProcess.js:946:242
	at processTicksAndRejections (internal/process/task_queues.js:94:5)```

**Comment by AidasPa** [comment]
temporary solution, run `npm i` in
`~/.vscode/extensions/jakebecker.elixir-ls-0.6.0`

**Comment by supercodepoet** [comment]
@AidasPa that temporary solution worked for me! Thanks.

**Comment by aleury** [comment]
I tried @AidasPa's solution and am now seeing these logs in the ElixirLS output:

```
No which executable found for nodejs 10.16.3
No which executable found for nodejs 10.16.3
** (UndefinedFunctionError) function ElixirLS.LanguageServer.CLI.main/0 is undefined (module ElixirLS.LanguageServer.CLI is not available)
    ElixirLS.LanguageServer.CLI.main()
    (stdlib 3.9.2) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.10.2) lib/code.ex:332: Code.eval_string_with_error_handling/3
```

**Comment by alfert** [comment]
I have the same effect as @aleury. Starting the language server by hand with `/language_server.sh` in `~/.vscode/extensions/jakebecker.elixir-ls-0.6.0/elixir-ls-release` results in: 

```
 [error] beam/beam_load.c(1883): Error loading module 'Elixir.ElixirLS.LanguageServer.CLI':
  This BEAM file was compiled for a later version of the run-time system than 22.
  To fix this, please recompile this module with an 22 compiler.
  (Use of opcode 169; this emulator supports only up to 168.)
```

So it seems that my Erlang installation is too old - but officially the language server should run with Erlang 21 as minimum.

**Comment by bceskavich** [comment]
I've also been experiencing this issue today. I tried @AidasPa's temporary workaround. But, like other commenters, I ran into issues when ElixirLS would start up.

I think I've identified a temporary workaround that does indeed work, based on @iporsut's comments that this is ultimately a `vsce` bug.

Steps:

1. Clone `vscode-elixir-ls` locally. Ensure the symlinked `elixir-ls` repo is also cloned to your local machine.
2. Install dependencies: `npm install`
3. Package the extension: `npx vsce package --no-yarn`
4. Install the packaged extension to your VSCode instance: `code --install-extension elixir-ls-0.6.0.vsix`

For more info, see the [Packaging extensions guide](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#packaging-extensions) from the VSCode docs.

**Comment by aimerib** [comment]
> 1. Clone `vscode-elixir-ls` locally. Ensure the symlinked `elixir-ls` repo is also cloned to your local machine.
> 2. Install dependencies: `npm install`
> 3. Package the extension: `npx vsce package --no-yarn`
> 4. Install the packaged extension to your VSCode instance: `code --install-extension elixir-ls-0.6.0.vsix`

Thank you! As a temporary solution, this worked great!

**Comment by zemuldo** [comment]
@bceskavich 's Solution works but the LS does not start for an umbrella project. Crashes with 
```shell
[Info - 10:05:32 PM] Connection to server got closed. 
Server will restart. ** (UndefinedFunctionError) function ElixirLS.LanguageServer.CLI.main/0 is undefined (module ElixirLS.LanguageServer.CLI is not available) ElixirLS.LanguageServer.CLI.main() (stdlib 3.11.2) erl_eval.erl:680: :erl_eval.do_apply/6 (elixir 1.10.0) lib/code.ex:332: Code.eval_string_with_error_handling/3 
[Info - 10:05:33 PM] Connection to server got closed. Server will restart. 
** (UndefinedFunctionError) function ElixirLS.LanguageServer.CLI.main/0 is undefined (module ElixirLS.LanguageServer.CLI is not available) ElixirLS.LanguageServer.CLI.main() (stdlib 3.11.2) erl_eval.erl:680: :erl_eval.do_apply/6 (elixir 1.10.0) lib/code.ex:332: Code.eval_string_with_error_handling/3 
[Error - 10:05:33 PM] Connection to server got closed. Server will not be restarted.
```

@AidasPa 's Installing ~/.vscode/extensions/jakebecker.elixir-ls-0.6.0 also did not work for me, led to some other error.

I resorted to the previous version. I will just try an update after the fix is made ☹️ 
<img width="485" alt="Screenshot 2020-10-04 at 22 16 51" src="https://user-images.githubusercontent.com/19955045/95025083-e959d280-068f-11eb-96b9-e0ff3c254502.png">

**Comment by axelson** [comment]
Sorry about this! After investigating it looks like there were two issues, one was that I was hit by https://github.com/microsoft/vscode-vsce/issues/494 which caused the extension to not start because the dependencies were not installed. This issue could be worked around with https://github.com/elixir-lsp/vscode-elixir-ls/issues/145#issuecomment-703249412

The second issue was that I built the package with Elixir 1.10, and that caused the extension to not run on any project using an earlier elixir version which caused the `function ElixirLS.LanguageServer.CLI.main/0 is undefined` error.

But the good new is that I just released v0.6.1 that fixes both those issues. Didn't make a PR but this is the commit that bumps the version and adds a reminder to use the `.release-tool-versions` when publishing the extension: https://github.com/elixir-lsp/vscode-elixir-ls/commit/6ef324bbb9ed0e1889eca9471bfec57f4a60ce6a

**Comment by cmuhire** [comment]
Thanks a lot for fixing @axelson :pray: 

The new version now launches and main features like autocomplete, navigation, docs and PLT build work however I can't seem to get the new Ecto completion feature working (I had successfully tested this earlier but with the local build of the extension in debug mode with the `Launch Extension` launch configuration).

I also get the following error in the extension log and some docsh warnings that reference the original build directory
![elixir_ls_errors](https://user-images.githubusercontent.com/6691440/95027167-c848b000-0696-11eb-911f-bd80aa6c0875.png)

Is anyone else experiencing the same scenario?
