### ISSUE TITLE
Build broken after 99b079220e20cf8f3545a8003b69166c130f3661

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lsp/vscode-elixir-ls#106]
```
> elixir-ls@0.4.0 compile /Users/lukaszsamson/vscode-elixir-ls
> tsc -p ./ && cd elixir-ls && mix elixir_ls.release -o ../elixir-ls-release

src/extension.ts:130:25 - error TS2532: Object is possibly 'undefined'.

130     const cwd: String = session.workspaceFolder.uri.toString().replace("file://", "");
                            ~~~~~~~~~~~~~~~~~~~~~~~

src/extension.ts:133:9 - error TS2532: Object is possibly 'undefined'.

133     if (executable.options) {
            ~~~~~~~~~~

src/extension.ts:134:22 - error TS2532: Object is possibly 'undefined'.

134       options = { ...executable.options, cwd };
                         ~~~~~~~~~~

src/extension.ts:139:46 - error TS2532: Object is possibly 'undefined'.

139     return new vscode.DebugAdapterExecutable(executable.command, executable.args, options);
                                                 ~~~~~~~~~~

src/extension.ts:139:66 - error TS2532: Object is possibly 'undefined'.

139     return new vscode.DebugAdapterExecutable(executable.command, executable.args, options);
                                                                     ~~~~~~~~~~

src/extension.ts:139:83 - error TS2345: Argument of type '{ cwd: String; env?: { [key: string]: string; } | undefined; }' is not assignable to parameter of type 'DebugAdapterExecutableOptions'.
  Types of property 'cwd' are incompatible.
    Type 'String' is not assignable to type 'string'.
      'string' is a primitive, but 'String' is a wrapper object. Prefer using 'string' when possible.

139     return new vscode.DebugAdapterExecutable(executable.command, executable.args, options);
                                                                                      ~~~~~~~


Found 6 errors.
```

**Comment by jayjun** [comment]
Fixed in #104.

**Comment by axelson** [comment]
#104 is now merged
